In [1]:
##課題1，2
import numpy as np

def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    y = np.sum(w*x) + b
    if y <= 0:
        return 0
    else:
        return 1

def NAND(x1, x2):
    x = np.array([x1,x2])
    w = np.array([-0.5,-0.5])
    b = 0.7
    y = np.sum(w*x) + b
    if y <= 0:
        return 0
    else:
        return 1

def OR(x1, x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.4
    y = np.sum(w*x)+b
    if y <= 0:
        return 0
    else:
        return 1

def XOR(x1, x2):
    s1 = NAND(x1,x2)
    s2 = OR(x1,x2)
    y = AND(s1,s2)
    return y

if __name__ == '__main__':
    print("AND")
    for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
        out = AND(xs[0], xs[1])
        print(str(xs) + " -> " + str(out))
        
    print("NAND")
    for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
        out = NAND(xs[0], xs[1])
        print(str(xs) + " -> " + str(out))
    
    print("OR")
    for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
        out = OR(xs[0], xs[1])
        print(str(xs) + " -> " + str(out))
    
    print("XOR")
    for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
        out = XOR(xs[0], xs[1])
        print(str(xs) + " -> " + str(out))

AND
(0, 0) -> 0
(1, 0) -> 0
(0, 1) -> 0
(1, 1) -> 1
NAND
(0, 0) -> 1
(1, 0) -> 1
(0, 1) -> 1
(1, 1) -> 0
OR
(0, 0) -> 0
(1, 0) -> 1
(0, 1) -> 1
(1, 1) -> 1
XOR
(0, 0) -> 0
(1, 0) -> 1
(0, 1) -> 1
(1, 1) -> 0


In [2]:
#課題3
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def softmax(x):
    c = np.max(x)
    exp_x = np.exp(x-c)
    sum_exp_x = np.sum(exp_x)
    y = exp_x/sum_exp_x
    return y

if __name__ == '__main__':
    x = np.array([-1.0, 1.0, 2.0])
    y = sigmoid(x)
    print("Sigmoid")
    print(y)
    z = softmax(x)
    print("Softmax")
    print(z)

Sigmoid
[0.26894142 0.73105858 0.88079708]
Softmax
[0.03511903 0.25949646 0.70538451]


In [4]:
#課題4
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def softmax(x):
    c = np.max(x)
    exp_x = np.exp(x-c)
    sum_exp_x = np.sum(exp_x)
    y = exp_x/sum_exp_x
    return y

def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network
def forward(network, x):
    # layer 1
    W1=network['W1']
    b1=network['b1']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    # layer2 layer3を実装してみてください 
    # layer 2
    W2=network['W2']
    b2=network['b2']
    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)
    # layer 3
    W3=network['W3']
    b3=network['b3']
    a3=np.dot(z2,W3)+b3
    y=softmax(a3)
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.31682708 0.69627909]

[[0.40625907 0.59374093]]


In [5]:
##以下、課題5

In [6]:
%%time
network = init_network()
batch_size = 16
x=np.random.rand(1000000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)

CPU times: user 2.44 s, sys: 11.9 ms, total: 2.45 s
Wall time: 2.47 s


In [7]:
%%time
network = init_network()
batch_size = 64
x=np.random.rand(1000000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)

CPU times: user 722 ms, sys: 15.9 ms, total: 737 ms
Wall time: 727 ms


In [8]:
%%time
network = init_network()
batch_size = 2
x=np.random.rand(1000000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)

CPU times: user 18.4 s, sys: 104 ms, total: 18.5 s
Wall time: 18.4 s


In [9]:
#バッチのサイズによって，実行時間に大きな差が見られた．